### ISSUE TITLE
서버 연결에 실패했습니다. 

### ISSUE THREAD

**Issue by BongsoonChoi** [gusdnd852/kochat#9]
![image](https://user-images.githubusercontent.com/50178886/88166804-d455d180-cc52-11ea-87da-32614aa8aca1.png)

먼저 올라온 이슈를 살펴보면서 config에서 모델 줄이고 학습 완료됬는데...
실행하니깐 서버 연결에 실패했다고 뜨네요

왜이럴까요..?

**Comment by BongsoonChoi** [comment]
main.js에서 ajax 요청하는 ip 바꾸고 나서 되긴 했습니다 다만 에폭을 낮춰서 학습시켯더니 인식을 못하는지 못알아먹네요...ㅠ

**Comment by gusdnd852** [comment]
intent랑 entity accuracy랑 f1스코어 몇까지 가셨나요?

**Comment by BongsoonChoi** [comment]
데모만을 가지고 학습량을 늘렸을때는 어느정도 성과가 나왔습니다. accuracy나 f1 score는 덮어쓰기 되어서 지금은 잘 모르겠네요..

새로운 intent를 추가해서 작업해봤는데 데이터셋을 직접 추가하려다보니 어려워서 600개 정도로 낮추고 기존 데모 데이터셋도 600개 정도로 낮췄더니 인식하긴 하는데 못할때도 많더라구요. accuracy나 f1 score가 100퍼나왔는데도..
일단 데이터가 많아야 어느정도 성과가 나오겠구나 하는 생각은 들었습니다.
물론 테스트용으로 한거다보니 저도 짧게밖에 하지 않았지만 실제 서비스로 적용한다치면 좋은 성과가 나올것이라 생각듭니다.

좋은 오픈소스 감사합니다~~!

**Comment by BongsoonChoi** [comment]
> intent랑 entity 학습하실때 accuracy랑 f1스코어 몇까지 가셨나요?

이후에 학습량을 늘리니까 제대로 인식하였습니다. accuracy나 f1 score는 제가 따로 남겨두지 않아서..ㅠ

추가로 intent 하나를 늘려서 작업해봤는데 데이터를 직접 만드려니 쉽지가 않아서 500개 정도만 만들고 나머지 데모 데이터셋도 500개정도로 낮췄습니다. 그리고 ood에서 관련된 문장들을 삭제해주었습니다.
그리고 학습해보니.. 어쨋든 accuracy나 f1score는 100퍼가 나오긴하지만 실제로 해보면 인식 못하는 경우도 있더라구요..

역시나 데이터가 많아야 성과가 있을듯 합니다. 실제 서비스에 적용된다면 조금더 낫지 않을까 생각해봅니다.
좋은 오픈소스 감사드려요~~!!!
